version: '3.8'
x-enviroment-defaults: &enviroment-defaults
  DEBUG: "True"
  DB_NAME: "taxi_app"
  DB_USER: "root"
  DB_PASSWORD: "root"
  DB_HOST: "postgres"
  DB_PORT: 5432
  CELERY_BROKER_URL: "redis://:1445464_redis@redis:6379"
  CELERY_BROKER_BACKEND: "redis://:1445464_redis@redis:6379"
  SECRET_KEY: "secret"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: taxi_app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - my_network

  web:
    build:
      context: .
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - postgres
      - redis
    environment:
      <<: *enviroment-defaults
    volumes:
      - static_volume:/app/static
    networks:
      - my_network

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/certs:/etc/nginx/certs/
      - static_volume:/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - my_network

  redis:
    image: redis:latest
    command: redis-server --requirepass 1445464_redis
    ports:
      - "6379:6379"
    networks:
      - my_network

volumes:
  static_volume:

networks:
  my_network:
    driver: bridge